### ISSUE TITLE
Great table. An error and a few things to add...

### ISSUE THREAD

**Issue by lukio3** [ratiw/vuetable-2-with-laravel-5.4#2]
Hey,

Love the table I just installed it on a test L5.4 site following your instructions and have it working. Just about to replace your dummy data with some of my own using axios.

A couple of things: 

1) the form html tag isn't closed in the filter bar .vue file and so laravel mix fails to compile.

2) you need to add the step:

 npm install --save accounting moment 

to your README. this isn't installed by default with L5.4 as far as i can tell. (without this laravel mix also fails)

Thanks

Luke

**Comment by mostafa6765** [comment]
please dear describe how success , I can'r laravel 5.4

**Comment by ratiw** [comment]
@lukio3 Thanks for the feedback. :)

**Comment by ratiw** [comment]
@lukio3 For the second point, the "Setting up" in the README is supposed to be a guide for using Vuetable-2 in your Laravel 5.4 project. So, if you do not use `accounting` and `moment` packages, you do not need it. Maybe it was not clear enough, I'll try to make it more clear.

**Comment by gustav1105** [comment]
How do I use the api route to my own project I get a 401 error.

**Comment by Jackchengwang** [comment]
I cannot install customaction package

**Comment by Gemini12** [comment]
Hi @ratiw I get this error when the table loads in the view. I currently cannot see any rows being displayed once the view renders. Can you assist please? Thanks in advance

> XMLHttpRequest cannot load http://vuetable.ratiw.net/api/users?sort=&page=1&per_page=5. Response for preflight is invalid (redirect)

> VM3314:1 XHR failed loading: GET "http://vuetable.ratiw.net/api/users?sort=&page=1&per_page=5".

> load-error Error: Network Error
