### ISSUE TITLE
npm install issue fix

### ISSUE THREAD

**Issue by g0ld3lux** [ratiw/vuetable-2-with-laravel-5.4#6]
fix for this is 
edit your packages.json and add dist before the bin
```
node node_modules/cross-env/dist/bin/cross-env.js
```
next install babel preset 2015 and create your .babelrc 
```
npm install babel preset 2015 --save
```

//.babelrc
```
{
  "presets": ["es2015"]
}
```

**Comment by rr5050** [comment]
Correction (atleast what I got to work) to the above comment from @g0ld3lux 
change this one as above (same as above):
`node node_modules/cross-env/dist/bin/cross-env.js`

And instead of doing the npm install as above and the babelrc file, you instead only do this:
`npm install --save-dev babel-preset-es2015`

**Comment by schumskie** [comment]
I still can't compile javascript. I got this error
 ```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "public" is not an absolute path!
```

**Comment by cringerjs** [comment]
@ByteRogue this is because the Laravel Mix version is outdated.  Run composer update to get the latest version.

**Comment by cringerjs** [comment]
This issue is resolved in GH-11

**Comment by ratiw** [comment]
Thanks @cringer for taking the time and sharing this.

**Comment by ergonomicus** [comment]
I don't know if the documentation is wrong or it's my setup that's wrong, but I had to install this in order to compile

`npm install accounting vue-events babel-preset-es2015 --save-dev`

Maybe it helps someone...

**Comment by cringerjs** [comment]
For this specific package babel-preset-es2015 is already listed in package.json
`"babel-preset-es2015": "^6.24.1",`

You should just need to do an npm install prior to compiling.

**Comment by ergonomicus** [comment]
@cringer I was following **Steps to use Vuetable-2 in your Laravel 5.4 project** part of readme, so I didn't have babel-preset-es2015 in my package.json...

Sure I did 'npm install' prior to compiling, maybe I misunderstood the point of this repo?? :)

**Comment by cringerjs** [comment]
Ok that does make sense if you didn't clone this repo and are adding to your existing Laravel 5.4 project.  In that case babel-presest-es2015 is not installed but it does have a step of "install additional babel plugins".  Though it says babel-preset-stage-2 not babel-preset-es2015.  Well have to look at that.

**Comment by cringerjs** [comment]
The readme instructions for using in your Laravel 5.4 project are incorrect.  If you clone the repository and launch it does work successfully.

I submitted PR #14 to update this information.
